version: '3.8'
services:
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-postgres}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-test@domain.local}'
      - 'PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-super_strong_password_not}'
      - PGADMIN_CONFIG_SERVER_MODE=True
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
  
  nginx:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - SERVICE_FQDN_PGADMINNGINX_80
    depends_on:
      pgadmin:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgresql-data: {}
  pgadmin-data: {}
